// Code generated by "stringer -type=Country"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Poland-0]
}

const _Country_name = "Poland"

var _Country_index = [...]uint8{0, 6}

func (i Country) String() string {
	if i < 0 || i >= Country(len(_Country_index)-1) {
		return "Country(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Country_name[_Country_index[i]:_Country_index[i+1]]
}
